ext
truekendor/better-ccc-extension pull request #28
Opened 2024-04-14 16:50 UTC by MrBrain295

2024-04-14 16:51 UTC, MrBrain295 commented
then you can just rename it from zip to xpi and it works on firefox

2024-04-14 16:51 UTC, MrBrain295 commented
nevermind firefox dosent work

2024-04-14 16:51 UTC, MrBrain295 commented
ill work on that

2024-04-14 16:54 UTC, truekendor commented
@MrBrain295 Many thanks, I don't understand much about workflows
So this will automatically build .xpi inside firefox dir ?

2024-04-14 16:56 UTC, MrBrain295 commented
well it dosent work as well as i thought. i will have to make some changes, but no it generates a extention file but nothing is automatic it is just something you can run on your computer

2024-04-14 17:48 UTC, MrBrain295 commented
ChatGPT made me a script that when run makes an extention that wokes for chrome (i installed chromium and tested it). I know firefox cant have the files in a directory in the archive but I cant figure out how to not do that. Here is the script `#!/bin/bash

# Define the directory to zip
SOURCE_DIR="./src"

# Define the output zip file
ZIP_FILE="extension.zip"

# Change directory to the source directory
cd "$SOURCE_DIR" || exit

# Zip all files except .ts files in the source directory
find . -type f ! -name "*.ts" -exec zip -u9 "../$ZIP_FILE" "{}" \;

# Go back to the original directory
cd ..

echo "Extension zipped successfully!"
`

2024-04-14 18:00 UTC, MrBrain295 commented
that formatted poorly

2024-04-14 18:02 UTC, MrBrain295 commented
[ext.txt](https://github.com/truekendor/better-ccc-extension/files/14971612/ext.txt)

2024-10-19 11:41 UTC, truekendor requested changes
Missing comma at the end of the line 11

2024-10-19 11:41 UTC, truekendor commented on package.json
>      "eslint": "^8.56.0"
Missing comma at the end of the line 11

2024-10-19 14:40 UTC, MrBrain295 commented
Eh I don’t think this is gonna work

2024-10-19 14:40 UTC, closed without merging